"""
Bundled Chronicle seed dumps shipped with the wheel.

Currently the package ships exactly one seed:

- ``pantheon_self.jsonl.gz`` — Theogony's own vision / strategy /
  doctrine layer (README, AGENTS.md, PHILOSOPHY, all docs/, all
  prompts/), generated by :func:`theogony.docs_ingest.regenerate.regenerate`.

The seed is imported into a configured :class:`KnowledgeStore` via
``theogony seed`` so a fresh install of Theogony has a meaningful
chronicle from the very first ``pantheon_ask`` call — the system can
describe itself before any external corpus is ingested.

Use :func:`pantheon_self_dump_path` to resolve the bundled file via
``importlib.resources``, which works whether the wheel is installed
in editable mode (``pip install -e .``) or as a built wheel
(``pip install theogony``).
"""

from __future__ import annotations

from importlib.resources import as_file, files
from pathlib import Path

#: Filename of the canonical self-seed dump.
PANTHEON_SELF_FILENAME = "pantheon_self.jsonl.gz"


def pantheon_self_dump_path() -> Path:
    """Return the on-disk path of the bundled ``pantheon_self`` dump.

    Uses ``importlib.resources`` so the lookup works against both
    editable and wheel-installed copies of the package. The returned
    path is always real (not zip-internal) because hatchling does not
    package files into zips for this layout.
    """
    resource = files(__package__).joinpath(PANTHEON_SELF_FILENAME)
    with as_file(resource) as p:
        return Path(p)


__all__ = [
    "PANTHEON_SELF_FILENAME",
    "pantheon_self_dump_path",
]
