"""Oneiros consolidation — merging entity candidates and regenerating what they say.

This is the load-bearing half of migration step S5 (`MESH_MIGRATION_PLAN.md`
§"Step S5"), and it exists because of a measurement rather than a plan.

`MESH_SUBSTRATE.md` §"Why two tiers" specifies **eager-when-clear,
emergent-when-not**: Kadmos links a reference to an existing Tier-1 node when
Q-ID, description or tag evidence decides it, and otherwise attaches a fresh
**entity candidate** (`is_candidate = True`) whose identity Oneiros settles
later. The second half was never built. On the founding mesh the consequence is
literal: **every one of the 3,783 entity nodes carries `is_candidate = True`**,
and Zeus is six of them —

    Zeus                     — King of the gods, son of Cronos, aegis-holder.
    son of Cronos            — Zeus, the king of the gods, who freed the Hecatoncheires.
    her father               — Zeus, the father of Persephone, who is called the Son of Cronos.
    father of men and gods   — Zeus, who speaks to the Hecatoncheires after they are freed.
    Son of Chronos           — A reference to Zeus, who granted frogs their dual nature.
    (a paragraph concept tagged Zeus and Thetis)

Two costs follow, and they are different costs. The evidence for one entity is
**split across several nodes**, so no node accumulates the potential its entity
earned; and the name a reader sees is the name of whichever *mention* created
the node, which is why a Constellation answering "who are the children of Cronus
and Rhea" showed `her father`, `Host of Many`, `dear mother` and `Vesta`
(PHX-1096). Merging fixes both at once: it is the same operation.

**What this module does not do.** S5 as specified is consolidation *plus* splits,
renormalisation, the pruner, pathology surveillance, therapy and three-factor RL.
This is consolidation only. Tier promotion (Tier 1 -> 2 -> 3) is specified as
earned through "number of distinct activation contexts, age, breadth of incoming
references" — and `fired_total` is **0 on every node in the substrate**, because
nothing on the read path increments it. Promotion would therefore be promotion by
age alone, so it is not implemented here; see PHX-1097 for the finding.

**Why an LLM decides the merges.** Tag evidence alone over-merges, and the
substrate itself shows how: the node `Daughter of Cronos — A goddess, daughter of
Cronos, likely Athena or Hestia` is tagged with *both* names. Any rule that
merges on a shared discriminating tag fuses Athena into Hestia. Doctrine puts a
small LLM call inside consolidation already (`MESH_SUBSTRATE.md` §"Consolidation
— promoting Tier 0 -> Tier 1": "a description regenerated by a small LLM call"),
and this is the same call answering the prior question. It is **not** an
insertion-time gate — the substrate's forbidden pre-gate is a `False` before a
chunk enters (§"What the substrate deliberately does not do", point 1). This runs
post-hoc over accumulated evidence, which is exactly where doctrine puts
identity decisions.

Structure of a pass:

    propose   cheap, pure substrate bookkeeping, no network  -> MergeProposal
    adjudicate  one small LLM call per proposal              -> MergeVerdict
    apply     rewire edges, fuse nodes, write the audit      -> ConsolidationResult
    regenerate  one small LLM call per surviving cluster     -> new description

Each stage is separately callable and separately testable, and `propose` alone is
a useful read-only report on how fragmented a substrate's identity is.
"""

from __future__ import annotations

import asyncio
import re
from collections import defaultdict
from collections.abc import Awaitable, Callable, Iterable, Sequence
from dataclasses import dataclass, field, replace
from datetime import UTC, datetime
from typing import Any, Protocol

from theogony.mesh.runtime.oneiros_tick import MeshRuntime
from theogony.mesh.schemas import ConsolidatedNode, Edge
from theogony.mesh.storage.edges import DEFAULT_MAX_OUT_DEGREE, enforce_saturation

# A tag is a candidate *name* only if it is capitalised in the source and rare
# enough to discriminate. The first half is what the extractor gives us: it
# writes type tags in lower case (`concept` on 2,799 founding-mesh nodes,
# `paragraph_concept` on 829) and names in upper case.
#
# The second half is a guard rather than the instrument, and the measurement says
# so plainly. Sweeping the ceiling on the founding mesh:
#
#     DF<=4    117 proposals
#     DF<=8    142
#     DF<=12   147
#     DF<=25   147      <- the default
#     DF<=100  147
#
# **It is inert above 12 here.** What actually removes the categorical tags is
# elsewhere: excluding paragraph concepts (which took `Greek mythology`'s 23
# false proposals with it) and keeping digits in a name (which stopped
# `Fragment #3` and `Fragment #37` from being one name). Both are category
# judgements about what a node *is*; a frequency threshold is neither, and
# tuning one to do their job would have hidden the reason.
#
# It stays because a substrate can carry a capitalised tag on thousands of nodes
# — `data/mesh-wiki-100k` is seeded from Wikidata, where type labels are
# capitalised — and one such tag would put every node carrying it into a single
# adjudication fan-out. 25 is a ceiling on the damage, not a decision about
# identity: the adjudicator makes those.
DEFAULT_MAX_NAME_DF = 25

# Below two nodes a name proposes nothing, by definition.
_MIN_NAME_DF = 2

# Tags on a merged node, most-evidenced first. The union of six Zeus nodes runs
# to a dozen names; the substrate's compression discipline applies to tags as
# much as to descriptions (`MESH_SUBSTRATE.md` §"Field discipline" point 4), and
# `assemble_constellation` reads only the first eight anyway.
_MAX_MERGED_TAGS = 12

# What a regenerated description may cost. Doctrine: "typically ~200-500 chars,
# and never a stored paragraph body".
MAX_DESCRIPTION_CHARS = 400


def normalise_name(raw: str | None) -> str:
    """Fold a name to its comparable core, **keeping digits**.

    The evaluator's fold (`eval/corpus_qa._normalise`) strips them, because it is
    matching a gold name against a corpus that carries inline footnote markers —
    a node is called `Hestia 1618` as readily as `Hestia`. Identity cannot afford
    the same licence: with digits stripped, `Fragment #3` and `Fragment #37` are
    one name, and so are `Berlin Papyri 9739` and `Berlin Papyri 10560`. Those are
    numbered things whose number *is* their identity.

    Measured on the founding mesh: 63 of 2,453 capitalised tags contain a digit
    and every one of them is a citation label — no entity name is disambiguated by
    a numeral here, so keeping them costs nothing and prevents that whole class of
    false grouping.
    """
    text = re.sub(r"[^a-z0-9\s]", " ", (raw or "").lower())
    return re.sub(r"\s+", " ", text).strip()


def description_head(node: ConsolidatedNode) -> str:
    """The name a reader sees — everything before the em dash (PHX-1065)."""
    return (node.description or "").split("—")[0].strip()


@dataclass(frozen=True)
class MergeProposal:
    """One candidate absorption: ``member`` may be the same entity as ``anchor``."""

    anchor_id: str
    member_id: str
    name: str
    signal: str
    shared_names: tuple[str, ...]
    description_score: float
    context_score: float


@dataclass(frozen=True)
class MergeVerdict:
    proposal: MergeProposal
    decision: str  # "same" | "different" | "uncertain"
    reason: str = ""

    @property
    def same(self) -> bool:
        return self.decision == "same"


@dataclass
class ConsolidationResult:
    """What one pass did, in the shape the audit record and the CLI both want."""

    nodes_before: int = 0
    nodes_after: int = 0
    edges_before: int = 0
    edges_after: int = 0
    proposals: int = 0
    adjudicated: int = 0
    verdict_counts: dict[str, int] = field(default_factory=dict)
    clusters_merged: int = 0
    nodes_absorbed: int = 0
    ambiguous_dropped: int = 0
    self_edges_dropped: int = 0
    edges_coalesced: int = 0
    descriptions_regenerated: int = 0
    description_fallbacks: int = 0
    # Which model settled these identities. Recorded on the result as well as in
    # the audit so that an exported pass can be replayed with its provenance
    # intact — a consolidation is a decision about what the substrate *is*, and
    # "some model, once" is not an answer to who made it.
    adjudicator_model: str = ""
    describer_model: str = ""
    audit_id: str | None = None
    dry_run: bool = False

    def as_detail(self) -> dict[str, Any]:
        return {
            "nodes_before": self.nodes_before,
            "nodes_after": self.nodes_after,
            "edges_before": self.edges_before,
            "edges_after": self.edges_after,
            "proposals": self.proposals,
            "adjudicated": self.adjudicated,
            "verdicts": dict(self.verdict_counts),
            "clusters_merged": self.clusters_merged,
            "nodes_absorbed": self.nodes_absorbed,
            "ambiguous_dropped": self.ambiguous_dropped,
            "self_edges_dropped": self.self_edges_dropped,
            "edges_coalesced": self.edges_coalesced,
            "descriptions_regenerated": self.descriptions_regenerated,
            "description_fallbacks": self.description_fallbacks,
            "adjudicator_model": self.adjudicator_model,
            "describer_model": self.describer_model,
        }


# ---------------------------------------------------------------- proposing


# A node the extractor wrote to summarise a *passage* rather than to name a
# thing — `MESH_SUBSTRATE.md` §"Worked example" calls these paragraph concepts,
# and Kadmos tags them. They are 829 of the founding mesh's 3,783 entity nodes,
# and they carry an entity's tags without being that entity: the node tagged
# `Demeter, journey, paragraph_concept` reads "The passage describes the goddess
# being led to the house of the father". Merging one into Demeter would fuse a
# summary of a passage into the goddess it is about.
#
# They are excluded from the pass on both sides — never a member, never an
# anchor. This is a category judgement, not a confidence one, so it belongs here
# rather than in the adjudicator: the first dry run proposed 23 of them for
# absorption into `Theogony` under the shared tag `Greek mythology`, and every
# one would have been a wrong merge no matter how well the question was asked.
PARAGRAPH_CONCEPT_TAG = "paragraph_concept"


def _is_paragraph_concept(node: ConsolidatedNode) -> bool:
    return PARAGRAPH_CONCEPT_TAG in node.tags


def _capitalised_names(node: ConsolidatedNode) -> set[str]:
    return {
        normalise_name(tag)
        for tag in node.tags
        if tag and tag[:1].isupper() and normalise_name(tag)
    }


def node_potentials(edges: Iterable[Edge]) -> dict[str, float]:
    """Summed incident edge weight per node — the substrate's own evidence measure.

    `MESH_SUBSTRATE.md` §"Pruning" calls this the node potential and uses it to
    judge which nodes have earned their place. Consolidation uses it for the same
    judgement at a smaller scale: which of several nodes claiming one name is the
    one the others should fold into.
    """
    potential: dict[str, float] = defaultdict(float)
    for edge in edges:
        weight = float(edge.weight)
        potential[str(edge.source_id)] += weight
        potential[str(edge.target_id)] += weight
    return dict(potential)


def _cosine(a: Sequence[float] | None, b: Sequence[float] | None) -> float:
    if not a or not b:
        return 0.0
    dot = sum(x * y for x, y in zip(a, b, strict=False))
    na = sum(x * x for x in a) ** 0.5
    nb = sum(x * x for x in b) ** 0.5
    if na == 0.0 or nb == 0.0:
        return 0.0
    return float(dot / (na * nb))


def propose_merges(
    nodes: Sequence[ConsolidatedNode],
    *,
    potentials: dict[str, float],
    adjacency: dict[str, set[str]] | None = None,
    max_name_df: int = DEFAULT_MAX_NAME_DF,
) -> list[MergeProposal]:
    """Find candidate absorptions. Pure bookkeeping — no network, no mutation.

    **Star-shaped, never transitive.** For each discriminating name, the node with
    the strongest claim to it becomes the *anchor*; every other node carrying that
    name is proposed as a *member*. A node that anchors any name can never be
    proposed as a member of another cluster.

    That restriction is the whole safety argument. Clustering by pairwise
    similarity chains — `Daughter of Cronos` matches Hestia, and it also matches
    Athena, so a transitive closure merges **Athena into Hestia** through it.
    Every general clustering formulation has this failure mode and it is silent:
    the resulting node looks like a well-evidenced hub. A star forbids it
    structurally rather than by threshold, which is worth the merges it defers —
    anchor-to-anchor fusion (`Vesta` and `Hestia` as two well-evidenced nodes)
    is left for a later pass with its own evidence bar.

    Anchor rank is `(the node's own displayed name is this name, node potential,
    age)`. The first term matters more than it looks: `Zeus — King of the gods` is
    the node that says what Zeus is, and `her father — Zeus, the father of
    Persephone` is a node that says what one passage called him.
    """
    adjacency = adjacency or {}
    by_name: dict[str, list[ConsolidatedNode]] = defaultdict(list)
    for node in nodes:
        if node.is_source_anchor or _is_paragraph_concept(node):
            continue
        for name in _capitalised_names(node):
            by_name[name].append(node)

    live = {
        name: members
        for name, members in by_name.items()
        if _MIN_NAME_DF <= len(members) <= max_name_df
    }

    def _anchor_key(node: ConsolidatedNode, name: str) -> tuple[int, float, float]:
        own_name = normalise_name(description_head(node)) == name
        return (
            1 if own_name else 0,
            potentials.get(str(node.id), 0.0),
            -node.born_at.timestamp(),
        )

    anchors: dict[str, str] = {}  # name -> anchor node id
    for name, members in live.items():
        anchors[name] = str(max(members, key=lambda n: _anchor_key(n, name)).id)
    anchor_ids = set(anchors.values())

    # One proposal per node PAIR, not per name. `her father` is tagged Zeus,
    # Jupiter and Jove and anchors to the same node under all three — one identity
    # question asked three times and paid for three times. The names that proposed
    # it are kept together on the proposal, because which names two nodes share is
    # the evidence an auditor will want to see.
    proposals: dict[tuple[str, str], MergeProposal] = {}
    for name, members in live.items():
        anchor_id = anchors[name]
        anchor = next(n for n in members if str(n.id) == anchor_id)
        anchor_names = _capitalised_names(anchor)
        anchor_neighbours = adjacency.get(anchor_id, set())
        for member in members:
            member_id = str(member.id)
            if member_id == anchor_id or member_id in anchor_ids:
                continue
            member_neighbours = adjacency.get(member_id, set())
            context = (
                len(anchor_neighbours & member_neighbours) / len(member_neighbours)
                if member_neighbours
                else 0.0
            )
            key = (anchor_id, member_id)
            held = proposals.get(key)
            if held is not None:
                proposals[key] = replace(
                    held,
                    shared_names=tuple(sorted({*held.shared_names, name})),
                    context_score=max(held.context_score, context),
                )
                continue
            proposals[key] = MergeProposal(
                anchor_id=anchor_id,
                member_id=member_id,
                name=name,
                signal="tag",
                shared_names=tuple(sorted(anchor_names & _capitalised_names(member))),
                description_score=_cosine(anchor.description_vector, member.description_vector),
                context_score=context,
            )
    return list(proposals.values())


# ------------------------------------------------------------- adjudicating

# The question is deliberately narrow, and the three-way answer is the point.
# A binary same/different forces a guess on the cases that most need not to be
# guessed — the substrate contains `Daughter of Cronos — A goddess, daughter of
# Cronos, likely Athena or Hestia`, which is a node whose own description says
# its identity is unresolved. Doctrine's bar for a destructive operation is
# "beyond 'this might be wrong' into 'this is demonstrably wrong'"
# (`MESH_SUBSTRATE.md` §"Removal of false information"); a merge is destructive,
# so anything that is not SAME leaves the substrate alone.
_ADJUDICATE_SYSTEM = (
    "You decide whether two entries in a knowledge base describe the same real entity. "
    "Answer with exactly one word: SAME, DIFFERENT, or UNCERTAIN.\n"
    "SAME — the entries are the same entity under different names, including an "
    "epithet, an alias, a translated or Roman/Greek equivalent name, or a phrase "
    "that refers to it ('her father', 'the son of Cronos').\n"
    "DIFFERENT — distinct entities, even when closely related. A parent, a child, a "
    "sibling, a place associated with the entity, or a work about it is DIFFERENT.\n"
    "UNCERTAIN — the evidence does not decide, including when an entry names two "
    "possible identities without choosing between them."
)


class Adjudicator(Protocol):
    """Decides one proposal. Implemented by :class:`LLMAdjudicator` and by tests."""

    async def judge(
        self, proposal: MergeProposal, anchor: ConsolidatedNode, member: ConsolidatedNode
    ) -> MergeVerdict: ...


def _entry(node: ConsolidatedNode) -> str:
    names = ", ".join(node.tags[:8]) or "(none)"
    return f"description: {node.description or '(none)'}\nnames on file: {names}"


class LLMAdjudicator:
    """Doctrine's "small LLM call", asking the identity question rather than writing.

    One call per proposal rather than a batch of pairs per call. The batched form
    is cheaper and was rejected: a single mis-parsed line silently shifts every
    later verdict in its batch onto the wrong pair, and the failure is invisible
    because each verdict remains individually plausible. At 726 proposals on the
    founding mesh, the saving is not worth an error mode nothing would catch.
    """

    def __init__(self, llm: Any, *, concurrency: int = 8, temperature: float = 0.0) -> None:
        self._llm = llm
        self._semaphore = asyncio.Semaphore(concurrency)
        self._temperature = temperature

    @property
    def model_id(self) -> str:
        return str(getattr(self._llm, "model_id", "") or "")

    async def judge(
        self, proposal: MergeProposal, anchor: ConsolidatedNode, member: ConsolidatedNode
    ) -> MergeVerdict:
        prompt = (
            f"Entry A\n{_entry(anchor)}\n\n"
            f"Entry B\n{_entry(member)}\n\n"
            "Do A and B describe the same entity? Answer SAME, DIFFERENT or UNCERTAIN."
        )
        async with self._semaphore:
            for attempt in range(3):
                try:
                    raw = await self._llm.complete(
                        prompt,
                        system=_ADJUDICATE_SYSTEM,
                        max_output_tokens=8,
                        temperature=self._temperature,
                    )
                    text = (getattr(raw, "text", None) or str(raw)).strip().upper()
                    for token in ("SAME", "DIFFERENT", "UNCERTAIN"):
                        if token in text:
                            return MergeVerdict(proposal, token.lower(), text[:40])
                    return MergeVerdict(proposal, "uncertain", f"unparsed: {text[:40]}")
                except Exception as exc:  # noqa: BLE001 - a provider error is not a verdict
                    if attempt == 2:
                        # A merge that could not be adjudicated must not happen.
                        return MergeVerdict(proposal, "uncertain", f"error: {type(exc).__name__}")
                    await asyncio.sleep(2.0 * (attempt + 1))
        return MergeVerdict(proposal, "uncertain", "exhausted")


class ReplayAdjudicator:
    """Replays verdicts an earlier pass recorded, keyed by the node pair.

    Two things need this. A consolidation pass is a decision about what the
    substrate *is*, so it has to be reproducible without paying for — or
    depending on the mood of — a second round of model calls. And it makes the
    downstream parameters (how edges coalesce, what the saturation cap does)
    testable in isolation: without it, changing `coalesce` and re-running would
    also change every identity decision underneath, and the comparison would
    measure both at once.

    A pair with no recorded verdict is `uncertain`, never `same`.
    """

    def __init__(self, decisions: dict[tuple[str, str], str], *, source: str = "") -> None:
        self._decisions = decisions
        self._source = source

    @property
    def model_id(self) -> str:
        return f"replay:{self._source or 'unknown'}"

    @classmethod
    def from_export(cls, payload: dict[str, Any]) -> ReplayAdjudicator:
        """Read the JSON `scripts/mesh_consolidate.py --out` writes."""
        decisions = {
            (str(row["anchor_id"]), str(row["member_id"])): str(row["decision"])
            for row in payload.get("verdicts", [])
        }
        source = str(payload.get("result", {}).get("adjudicator_model", "") or "")
        return cls(decisions, source=source)

    async def judge(
        self, proposal: MergeProposal, anchor: ConsolidatedNode, member: ConsolidatedNode
    ) -> MergeVerdict:
        decision = self._decisions.get((proposal.anchor_id, proposal.member_id), "uncertain")
        return MergeVerdict(proposal, decision, "replayed")


async def adjudicate(
    proposals: Sequence[MergeProposal],
    nodes_by_id: dict[str, ConsolidatedNode],
    adjudicator: Adjudicator,
) -> list[MergeVerdict]:
    verdicts = await asyncio.gather(
        *(
            adjudicator.judge(p, nodes_by_id[p.anchor_id], nodes_by_id[p.member_id])
            for p in proposals
        )
    )
    return list(verdicts)


def resolve_clusters(verdicts: Sequence[MergeVerdict]) -> tuple[dict[str, str], set[str]]:
    """Turn verdicts into a member -> anchor map, refusing the members that fit twice.

    A node proposed against two anchors and adjudicated SAME against both cannot
    be both entities, and the substrate has no way to tell which verdict is the
    wrong one. It is dropped from the pass rather than merged into whichever
    scored higher — the ambiguity is real evidence about that node, and guessing
    would spend it. It stays in the substrate untouched and can be settled by a
    later pass with more evidence, which is what an entity candidate is for.

    Returns ``(remap, ambiguous)``.
    """
    accepted: dict[str, list[str]] = defaultdict(list)
    for verdict in verdicts:
        if verdict.same:
            accepted[verdict.proposal.member_id].append(verdict.proposal.anchor_id)

    remap: dict[str, str] = {}
    ambiguous: set[str] = set()
    for member_id, anchor_ids in accepted.items():
        distinct = set(anchor_ids)
        if len(distinct) > 1:
            ambiguous.add(member_id)
            continue
        remap[member_id] = distinct.pop()
    return remap, ambiguous


# ------------------------------------------------------------------ fusing


def fuse_nodes(anchor: ConsolidatedNode, members: Sequence[ConsolidatedNode]) -> ConsolidatedNode:
    """Build the surviving node from the anchor and everything it absorbs.

    The anchor keeps its ULID. Doctrine phrases the operation as "merges a
    candidate into an existing entity", and keeping the identifier is what makes
    it that rather than a replacement: every edge and every audit record that
    already names the anchor stays true.

    Counters sum, timestamps take the outer bound, names and Q-IDs union. The
    vectors stay the anchor's for now and are recomputed from the regenerated
    description in :func:`regenerate_descriptions` — `MESH_SUBSTRATE.md`
    §"Field discipline" point 4: "When the description changes (regeneration),
    `description_vector` is recomputed from it."

    ``is_candidate`` flips to False on the survivor and only there. Doctrine
    flips it "once convergence is reached"; a node that has absorbed another
    node's evidence has converged, and a node that absorbed nothing has not.
    That leaves most of the substrate still flagged as candidate, which is the
    honest reading of a mesh whose identity has never been settled.
    """
    all_nodes = [anchor, *members]

    tags: list[str] = []
    seen_tags: set[str] = set()
    for node in all_nodes:
        for tag in node.tags:
            key = normalise_name(tag)
            if not key or key in seen_tags:
                continue
            seen_tags.add(key)
            tags.append(tag)

    qids = list(anchor.qids)
    known_qids = {q.qid for q in qids}
    for node in members:
        for qid in node.qids:
            if qid.qid not in known_qids:
                known_qids.add(qid.qid)
                qids.append(qid)

    return anchor.model_copy(
        update={
            "born_at": min(n.born_at for n in all_nodes),
            "last_fired_at": max(n.last_fired_at for n in all_nodes),
            "fired_total": sum(n.fired_total for n in all_nodes),
            "fired_recent": sum(n.fired_recent for n in all_nodes),
            "positive_feedback_total": sum(n.positive_feedback_total for n in all_nodes),
            "negative_feedback_total": sum(n.negative_feedback_total for n in all_nodes),
            "feedback_recent": sum(n.feedback_recent for n in all_nodes),
            "is_candidate": False,
            "tags": tags[:_MAX_MERGED_TAGS],
            "qids": qids,
            # The node's own record of when it consolidated. Doctrine describes
            # this field as tier-promotion history; the substrate has no tier
            # promotion to record (nothing increments the counters it would be
            # earned on), and a merge is the consolidation event that did happen.
            "consolidation_history": [*anchor.consolidation_history, datetime.now(UTC)],
            # Both are caches over a topology this merge just changed.
            "node_potential_cache": None,
            "activation_entropy": None,
        }
    )


def rewire_edges(
    edges: Sequence[Edge],
    remap: dict[str, str],
    *,
    w_max: float = 1.0,
    coalesce: str = "sum",
) -> tuple[list[Edge], int, int]:
    """Point every edge of an absorbed node at its anchor.

    Returns ``(edges, self_edges_dropped, coalesced)``.

    **Self-edges are dropped only when the merge created them.** An edge whose
    endpoints were already equal is left alone: the CSR builder has explicit
    handling for self-loops (`tests/mesh/test_storage_csr_self_loops.py`), so
    they are a state the substrate supports, and silently removing them here
    would make consolidation a second thing — a self-loop pruner — that nobody
    asked it to be.

    **Coalescing sums.** Two nodes that both asserted `-> Cronos` were two
    independent observations of one relation, and convergent evidence is what
    the substrate's Hebbian rule accumulates. This differs from
    :func:`merge_edge_deltas`, which keeps the strongest of a duplicate triple,
    and the difference is deliberate: there the duplicates are the *same* node's
    row appended once per occurrence, so summing would count one observation
    many times. Here they come from different nodes. ``coalesce="max"`` keeps the
    other rule for callers who want to compare.
    """
    if coalesce not in {"sum", "max"}:
        raise ValueError(f"coalesce must be 'sum' or 'max', got {coalesce!r}")

    by_key: dict[tuple[str, str, str | None], Edge] = {}
    self_dropped = 0
    coalesced = 0
    for edge in edges:
        old_source, old_target = str(edge.source_id), str(edge.target_id)
        source = remap.get(old_source, old_source)
        target = remap.get(old_target, old_target)
        if source == target and old_source != old_target:
            self_dropped += 1
            continue
        key = (source, target, edge.relation_descriptor)
        existing = by_key.get(key)
        if existing is None:
            by_key[key] = edge.model_copy(update={"source_id": source, "target_id": target})
            continue
        coalesced += 1
        weight = (
            min(w_max, existing.weight + edge.weight)
            if coalesce == "sum"
            else max(existing.weight, edge.weight)
        )
        # Metadata follows the stronger contributor; the weaker one has no claim
        # to describe the fused relation.
        winner = existing if existing.weight >= edge.weight else edge
        by_key[key] = winner.model_copy(
            update={
                "source_id": source,
                "target_id": target,
                "weight": weight,
                "born_at": min(existing.born_at, edge.born_at),
                "last_fired_at": max(existing.last_fired_at, edge.last_fired_at),
            }
        )
    return list(by_key.values()), self_dropped, coalesced


# ------------------------------------------------------------ regenerating

# Doctrine's own words for what a Tier-1 description is: "short discriminating
# text — for entities: name + key discriminators", regenerated by Oneiros "from
# the strongest currently-resonant chunks". The strongest evidence available to a
# merge is the members' own descriptions, which is what the extractor wrote from
# those chunks — no raw source text is read, and none may be
# (`MESH_SUBSTRATE.md` §"What the substrate deliberately does not do", point 2).
_DESCRIBE_SYSTEM = (
    "You write one-line entries for a knowledge base. You are given several entries "
    "that have been found to describe the same entity, written from different "
    "mentions of it. Write one entry that replaces them all.\n"
    "Reply in exactly this form, two lines:\n"
    "NAME: <the entity's own name, not an epithet or a phrase referring to it>\n"
    "SUMMARY: <one sentence of what it is, under 250 characters>\n"
    "Use the name the entries agree on. Prefer the plain name over an epithet "
    "('Hades', not 'Host of Many'); prefer the name the entries use to the name of "
    "an equivalent from another culture ('Hestia', not 'Vesta'). Keep every "
    "discriminating fact the entries agree on. Add nothing you were not given."
)


class Describer(Protocol):
    async def describe(
        self, survivor: ConsolidatedNode, members: Sequence[ConsolidatedNode]
    ) -> tuple[str, str]: ...


def _parse_description(raw: str) -> tuple[str, str]:
    name, summary = "", ""
    for line in raw.splitlines():
        stripped = line.strip()
        if stripped.upper().startswith("NAME:"):
            name = stripped[5:].strip()
        elif stripped.upper().startswith("SUMMARY:"):
            summary = stripped[8:].strip()
    return name, summary


class LLMDescriber:
    def __init__(self, llm: Any, *, concurrency: int = 8) -> None:
        self._llm = llm
        self._semaphore = asyncio.Semaphore(concurrency)

    @property
    def model_id(self) -> str:
        return str(getattr(self._llm, "model_id", "") or "")

    async def describe(
        self, survivor: ConsolidatedNode, members: Sequence[ConsolidatedNode]
    ) -> tuple[str, str]:
        entries = "\n\n".join(_entry(n) for n in (survivor, *members))
        async with self._semaphore:
            for attempt in range(3):
                try:
                    raw = await self._llm.complete(
                        f"{entries}\n\nWrite the replacement entry.",
                        system=_DESCRIBE_SYSTEM,
                        max_output_tokens=160,
                        temperature=0.0,
                    )
                    return _parse_description(getattr(raw, "text", None) or str(raw))
                except Exception:  # noqa: BLE001 - a provider error is not a description
                    if attempt == 2:
                        return "", ""
                    await asyncio.sleep(2.0 * (attempt + 1))
        return "", ""


def compose_description(
    survivor: ConsolidatedNode,
    members: Sequence[ConsolidatedNode],
    name: str,
    summary: str,
) -> tuple[str, bool]:
    """Turn a model's two lines into a stored description, or refuse them.

    Returns ``(description, used_fallback)``.

    **The name is checked against the node's own names, and a name the substrate
    does not already hold is rejected.** This is the guard PHX-1065 paid for:
    the label index and the eager linker both key on the head of the description,
    so a regeneration that renamed a node to something plausible-but-new would
    make it unreachable by every name it had — while deleting the nodes that
    carried those names in the same pass. A model that answers `Jupiter` for a
    cluster whose members all say Zeus is answering a different question than the
    one identity needs.
    """
    known = {normalise_name(tag) for n in (survivor, *members) for tag in n.tags}
    known |= {normalise_name(description_head(n)) for n in (survivor, *members)}
    chosen = name if normalise_name(name) in known and name.strip() else ""
    if not chosen:
        chosen = description_head(survivor)
    body = " ".join(summary.split())
    if not body:
        # Nothing usable came back. The anchor's own description is still the best
        # thing the substrate has, and leaving it is a smaller error than writing
        # a bare name over it.
        return (survivor.description or chosen), True
    composed = _entity_description(chosen, body)
    if len(composed) > MAX_DESCRIPTION_CHARS:
        composed = composed[: MAX_DESCRIPTION_CHARS - 1].rstrip() + "…"
    return composed, not (normalise_name(name) in known and name.strip())


def _entity_description(label: str, description: str) -> str:
    """Name at the head, discriminators after it (`kadmos_v2._entity_description`).

    Duplicated rather than imported: `kadmos_v2` is the ingestion pipeline and
    pulls in the reading model, the vectorizer and the linker behind it. The
    substrate's maintenance pass must not depend on its writer. The rule itself is
    doctrine (`MESH_SUBSTRATE.md` §"Tier-1+ — Consolidated Node"), and
    `tests/mesh/test_entity_name_survives_write.py` pins both spellings of it.
    """
    name = (label or "").strip()
    body = (description or "").strip()
    if not name:
        return body
    if not body:
        return name
    if body.lower().startswith(name.lower()):
        return body
    return f"{name} — {body}"


# --------------------------------------------------------------- the pass


EmbedMany = Callable[[list[str]], Awaitable[list[list[float]]]]

# The audit action. Deliberately **not** `mesh_oneiros_minimal_tick`:
# `MeshRuntime.tick_count()` counts rows by that action, and it is the number
# every recall figure in this repo is quoted against. A consolidation filed under
# the tick's name would inflate it permanently — the log is append-only — and the
# one number that makes two benchmarks comparable would stop meaning anything.
CONSOLIDATION_ACTION = "mesh_oneiros_consolidation"


async def run_consolidation(
    runtime: MeshRuntime,
    *,
    adjudicator: Adjudicator | None = None,
    describer: Describer | None = None,
    embed: EmbedMany | None = None,
    max_name_df: int = DEFAULT_MAX_NAME_DF,
    coalesce: str = "sum",
    w_max: float = 1.0,
    max_out_degree: int = DEFAULT_MAX_OUT_DEGREE,
    dry_run: bool = False,
) -> tuple[ConsolidationResult, list[MergeProposal], list[MergeVerdict]]:
    """One consolidation pass over the whole substrate.

    Without an ``adjudicator`` this proposes and stops, which is a useful
    read-only report in its own right: it says how fragmented the substrate's
    identity is without changing anything and without a network call. Honest
    failure rather than a silent heuristic — an unadjudicated merge is not a
    merge this module is willing to make.

    **Write order is edges first, then nodes, and the audit before both.** The
    anchor keeps its ULID, so an edge table committed against nodes that were not
    yet rewritten still points at nodes that exist; the reverse order would leave
    every rewired edge pointing at a row that had just been deleted. Lance gives
    no transaction across tables (`EdgeStore.replace_all_edges` says so), so the
    ordering is the only protection there is, and the audit record is written
    first so that a half-applied pass is at least diagnosable.
    """
    nodes = list(runtime.nodes.iter_consolidated(page_size=1024))
    nodes_by_id = {str(n.id): n for n in nodes}
    edges = runtime.edges.load_all_edges()

    proposals = propose_merges(
        nodes,
        potentials=node_potentials(edges),
        adjacency=runtime.edges.adjacency_index(),
        max_name_df=max_name_df,
    )
    result = ConsolidationResult(
        nodes_before=len(nodes),
        edges_before=len(edges),
        proposals=len(proposals),
        dry_run=dry_run or adjudicator is None,
        adjudicator_model=str(getattr(adjudicator, "model_id", "") or ""),
        describer_model=str(getattr(describer, "model_id", "") or ""),
    )
    if adjudicator is None or dry_run:
        return result, proposals, []

    verdicts = await adjudicate(proposals, nodes_by_id, adjudicator)
    result.adjudicated = len(verdicts)
    counts: dict[str, int] = defaultdict(int)
    for verdict in verdicts:
        counts[verdict.decision] += 1
    result.verdict_counts = dict(counts)

    remap, ambiguous = resolve_clusters(verdicts)
    result.ambiguous_dropped = len(ambiguous)
    if not remap:
        return result, proposals, verdicts

    clusters: dict[str, list[ConsolidatedNode]] = defaultdict(list)
    for member_id, anchor_id in remap.items():
        clusters[anchor_id].append(nodes_by_id[member_id])
    result.clusters_merged = len(clusters)
    result.nodes_absorbed = len(remap)

    survivors = {
        anchor_id: fuse_nodes(nodes_by_id[anchor_id], members)
        for anchor_id, members in clusters.items()
    }

    if describer is not None:
        regenerated = await asyncio.gather(
            *(
                describer.describe(survivors[anchor_id], clusters[anchor_id])
                for anchor_id in survivors
            )
        )
        texts: list[str] = []
        order = list(survivors)
        for anchor_id, (name, summary) in zip(order, regenerated, strict=True):
            description, fallback = compose_description(
                nodes_by_id[anchor_id], clusters[anchor_id], name, summary
            )
            result.descriptions_regenerated += 1
            result.description_fallbacks += int(fallback)
            survivors[anchor_id] = survivors[anchor_id].model_copy(
                update={
                    "description": description,
                    "description_generated_at": datetime.now(UTC),
                    # Doctrine's audit trail for a regeneration. The evidence a
                    # merge regenerates from is the absorbed nodes, not Tier-0
                    # chunks, so this records the nodes — which is what the field
                    # has to mean for a substrate whose entity descriptions were
                    # never chunk-derived in the first place.
                    "description_source_chunks": [n.id for n in clusters[anchor_id]],
                }
            )
            texts.append(description)
        if embed is not None and texts:
            vectors = await embed(texts)
            for anchor_id, vector in zip(order, vectors, strict=True):
                survivors[anchor_id] = survivors[anchor_id].model_copy(
                    update={"semantic_vector": vector, "description_vector": vector}
                )

    surviving_nodes = [
        survivors.get(str(node.id), node) for node in nodes if str(node.id) not in remap
    ]
    rewired, self_dropped, coalesced = rewire_edges(edges, remap, w_max=w_max, coalesce=coalesce)
    rewired = enforce_saturation(rewired, max_out_degree=max_out_degree, w_max=w_max)
    result.self_edges_dropped = self_dropped
    result.edges_coalesced = coalesced
    result.nodes_after = len(surviving_nodes)
    result.edges_after = len(rewired)

    out_degree: dict[str, int] = defaultdict(int)
    for edge in rewired:
        out_degree[str(edge.source_id)] += 1
    peak = max(out_degree.values(), default=0)

    result.audit_id = runtime.audit.append(
        action=CONSOLIDATION_ACTION,
        detail={
            **result.as_detail(),
            "max_name_df": max_name_df,
            "coalesce": coalesce,
            "peak_out_degree": peak,
            "max_out_degree": max_out_degree,
            # The merged-away ULIDs exist nowhere else after this pass. There is
            # no field on ConsolidatedNode in which to record what a node
            # absorbed, so this record is the only way to read any artefact that
            # cites a pre-merge node id — a run report, an older Constellation.
            "absorbed": {
                anchor_id: [str(n.id) for n in members] for anchor_id, members in clusters.items()
            },
            "ambiguous": sorted(ambiguous),
        },
    )

    # The durable sidecar holds reinforcement written by earlier `mesh ask
    # --hebbian` runs as raw id strings. `merge_edge_deltas` *creates* an edge for
    # any key it does not find, so one pending delta naming an absorbed node would
    # have the next tick mint an edge to a row that no longer exists. Remapped
    # first, because the anchor id is stable: if the pass then fails, the deltas
    # name a live node either way.
    pending = runtime.edges.delta.drain()
    for row in pending:
        source = str(row["source_id"])
        target = str(row["target_id"])
        runtime.edges.delta.append_hebbian_delta(
            source_id=remap.get(source, source),
            target_id=remap.get(target, target),
            weight_delta=float(row["weight_delta"]),
            relation_descriptor=row.get("relation_descriptor"),
        )

    runtime.edges.replace_all_edges(rewired)
    runtime.nodes.replace_all_consolidated(surviving_nodes)
    runtime.invalidate_csr_cache()
    # `mode="overwrite"` drops the table's Lance indices with its data, and the
    # default refresh threshold (512 rows outside the index) will not rebuild
    # them for a pass this size. Without this the substrate silently reverts to
    # the pre-PHX-1059 full-scan cost on every identity lookup.
    runtime.nodes.ensure_indices(max_unindexed=1)
    return result, proposals, verdicts
