#!/usr/bin/env bash
set -euo pipefail

# Cockpit standalone uses Neo4j for the chronicle by default
# (THEOGONY_COCKPIT__KNOWLEDGE_STORE=neo4j). For offline runs without Bolt:
#   export THEOGONY_COCKPIT__KNOWLEDGE_STORE=memory

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export THEOGONY_CURIOSITY__GROWTH_BRIDGE__ENABLED="${THEOGONY_CURIOSITY__GROWTH_BRIDGE__ENABLED:-true}"
export THEOGONY_CURIOSITY__ARGUS__ENABLED="${THEOGONY_CURIOSITY__ARGUS__ENABLED:-true}"
export THEOGONY_CURIOSITY__RESEARCH_PLANNER__ENABLED="${THEOGONY_CURIOSITY__RESEARCH_PLANNER__ENABLED:-true}"
export THEOGONY_CURIOSITY__EVALUATOR__ENABLED="${THEOGONY_CURIOSITY__EVALUATOR__ENABLED:-true}"
export THEOGONY_CURIOSITY__ATHENE__ENABLED="${THEOGONY_CURIOSITY__ATHENE__ENABLED:-true}"
export THEOGONY_CURIOSITY__CHRONOS__ENABLED="${THEOGONY_CURIOSITY__CHRONOS__ENABLED:-true}"
export THEOGONY_CURIOSITY__NEMESIS__ENABLED="${THEOGONY_CURIOSITY__NEMESIS__ENABLED:-true}"
export THEOGONY_CURIOSITY__ERIS__ENABLED="${THEOGONY_CURIOSITY__ERIS__ENABLED:-true}"
export THEOGONY_MNEMOSYNE__CONDUCTOR_ENABLED="${THEOGONY_MNEMOSYNE__CONDUCTOR_ENABLED:-true}"

exec "${THEOGONY_PYTHON_BIN:-venv/bin/theogony}" cockpit serve --host "${HOST:-127.0.0.1}" --port "${PORT:-8000}"
