#!/usr/bin/env bash
set -euo pipefail

# Wave 3 Cockpit: in-memory Chronik with bundled pantheon_self seed on startup
# (see ``src/theogony/cockpit/standalone_app.py`` and
# ``docs/etappes/RETIREMENT_NEO4J_MULTIHOP.md``).

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

export THEOGONY_CURIOSITY__GROWTH_BRIDGE__ENABLED="${THEOGONY_CURIOSITY__GROWTH_BRIDGE__ENABLED:-true}"
export THEOGONY_CURIOSITY__ARGUS__ENABLED="${THEOGONY_CURIOSITY__ARGUS__ENABLED:-true}"
export THEOGONY_CURIOSITY__RESEARCH_PLANNER__ENABLED="${THEOGONY_CURIOSITY__RESEARCH_PLANNER__ENABLED:-true}"
export THEOGONY_CURIOSITY__EVALUATOR__ENABLED="${THEOGONY_CURIOSITY__EVALUATOR__ENABLED:-true}"
export THEOGONY_CURIOSITY__ATHENE__ENABLED="${THEOGONY_CURIOSITY__ATHENE__ENABLED:-true}"
export THEOGONY_CURIOSITY__CHRONOS__ENABLED="${THEOGONY_CURIOSITY__CHRONOS__ENABLED:-true}"
export THEOGONY_CURIOSITY__NEMESIS__ENABLED="${THEOGONY_CURIOSITY__NEMESIS__ENABLED:-true}"
export THEOGONY_CURIOSITY__ERIS__ENABLED="${THEOGONY_CURIOSITY__ERIS__ENABLED:-true}"
export THEOGONY_MNEMOSYNE__CONDUCTOR_ENABLED="${THEOGONY_MNEMOSYNE__CONDUCTOR_ENABLED:-true}"

exec "${THEOGONY_PYTHON_BIN:-.venv/bin/theogony}" cockpit serve --host "${HOST:-127.0.0.1}" --port "${PORT:-8000}"
